### ISSUE TITLE
Open files as UTF-8

### ISSUE THREAD

**Issue by 34j** [0xWelt/BibTeX-Formatter#1]
https://github.com/Nickydusk/BibTeX-Formatter/blob/a0e20fa58fd75ccf298e6d9e22e6ff6c0419f6dd/bfm/format.py#L377
This may cause the following error in certain environments:
```shell
UnicodeDecodeError: 'cp932' codec can't decode byte 0x86 in position 545: illegal multibyte sequence
```

**Comment by 0xWelt** [comment]
Thanks. Seems an issue when default decoding is set to cp932 for Japanese. I've tried to fix it in the most recent commit. Please check whether it works.

**Comment by 34j** [comment]
It now works perfectly. Thanks.
