### ISSUE TITLE
Handle arxiv paper

### ISSUE THREAD

**Issue by xuhangc** [0xWelt/BibTeX-Formatter#2]
It seems that currently this tool cannot handle arxiv paper and other manual or misc notation very well. It would be nice if it is compatible with arxiv

```
bib.fields['journal'] = f"arXiv preprint arXiv:{bib.fields['eprint']}"
KeyError: 'eprint'
```

**Comment by 0xWelt** [comment]
Thank you for your comment. In fact, arXiv is one of our main focuses, and currently, we support three formats: Google Scholar, arXiv official website's export format, and DBLP. May I ask if you have used a format that is not among the three mentioned? You can share your bibtex entry.

**Comment by xuhangc** [comment]
Hi, I think it is because there are special characters in the entry. I have already solved it.
